# Site settings

title: Kate Lanyon # Title of your site
# email: kate@katalisha.com # Your contant email

description: > # Kate Lanyon - web, iOS, agile, startups
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://katalisha.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     katalisha  # Replace this with your Twitter username
github_username:      katalisha  # Replace this with your GitHub username
linkedin_username:    katalisha  # Replace this with your LinkedIn username


# Build settings
markdown: kramdown
